### ISSUE TITLE
Have you ever tested it on the web?

### ISSUE THREAD

**Issue by apps-transround** [yungzhu/flutter_link_preview#1]
You`re saying Android, IOS, web.

Are you sure?

**Comment by yungzhu** [comment]
The web version has a cross-domain request issue and needs to be allowed to display content across domains

**Comment by yungzhu** [comment]
I changed the support platform.

**Comment by cableman127** [comment]
What does that mean? I just tried on Flutter Web for Chrome. I get XML CORS errors still. Also dart:io package doesn't work with flutter web. Should try universal_io package instead. Works for all platforms.

**Comment by yungzhu** [comment]
Because of cross-domain issues, temporarily unable to support the web platform

**Comment by JayPerfetto** [comment]
has there been any progress on this issue?
