### ISSUE TITLE
Flutter link preview does not work on certain urls

### ISSUE THREAD

**Issue by cableman127** [yungzhu/flutter_link_preview#2]
Example: https://youtu.be/ZawwHr7H0pw

Should have some case where there is no title or description found.

Some websites dont have opengraph configured so they dont have previews

**Comment by yungzhu** [comment]
The latest version fixes this issue

**Comment by cableman127** [comment]
Tipped you BAT via brave browser, you should make a BRAVE token account to get contributions

**Comment by yungzhu** [comment]
Thanks for your advice,but not for the moment

**Comment by kunalmanocha98** [comment]
Get web info empty(https://youtu.be/4veh0kLaXHk)

this is not fixed yet
version : 1.5.6

**Comment by KennyChan94** [comment]
> Get web info empty(https://youtu.be/4veh0kLaXHk)
> 
> this is not fixed yet
> version : 1.5.6

this link works for me, maybe the video was too new when you tried to get the web info? youtube had not prepared the video with the metadata yet?

**Comment by KennyChan94P** [comment]
> Get web info empty(https://youtu.be/4veh0kLaXHk)
> 
> this is not fixed yet
> version : 1.5.6

this link works for me, maybe the video was too new when you tried to get the web info? youtube had not prepared the video with the metadata yet?
